name = "SolverLogger"
uuid = "e6462751-90cf-4f5c-beb8-edae317af041"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.6"
